- name: deploy to kube cluster
  hosts: "{{ env }}"
  tasks: 
    - name: clone the cd repo
      git:
       repo: "https://github.com/lerndevops/it-services-portal-cd.git"
       dest: "/opt/it-services-portal-cd"
       version: "plain-yaml"
       clone: yes
       update: yes
    - name: deploy application 
      shell: "kubectl apply -f /opt/it-services-portal/k8s-deploy/releases/dev/*.yaml"
      when: env == "dev"
